require "game.mock_fbinstant"
local xoxo = require "xoxo.xoxo"
local xoxo_fbinstant = require "game.xoxo_fbinstant"

function init(self)
	-- the game client is ready
	-- we can proceed with setup of fbinstant
	xoxo.on_connect(function()
		xoxo_fbinstant.initialize(function(ok, err)
			if not ok then
				print(err)
				return
			end
			msg.post(".", "acquire_input_focus")
			xoxo_fbinstant.start()
		end)
	end)
end
